# Generated by Django 4.2.11 on 2024-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='img/%y/%m')),
                ('room_name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=155)),
                ('services', models.CharField()),
                ('price', models.CharField()),
            ],
        ),
    ]
