# Generated by Django 4.2.11 on 2024-03-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%Y/%m')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.room')),
            ],
        ),
    ]
