# Generated by Django 4.2.11 on 2024-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_room_image_alter_room_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('video_bg_image', models.ImageField(upload_to='img/%y/%m')),
                ('play_icon', models.ImageField(upload_to='img/%y/%m')),
            ],
        ),
    ]
