# Generated by Django 4.2.11 on 2024-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aboutvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
