# Generated by Django 4.2.11 on 2024-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptive_info',
            field=models.CharField(blank=True),
        ),
    ]
