# Generated by Django 4.2.11 on 2024-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
