# Generated by Django 4.2.11 on 2024-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_aboutvideo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='img/%y/%m')),
                ('service_title', models.CharField(max_length=55)),
                ('service_description', models.CharField(null=True)),
            ],
        ),
    ]
