# Generated by Django 4.2.11 on 2024-03-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_extraservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraServices',
            new_name='ExtraService',
        ),
    ]
