# Generated by Django 4.2.11 on 2024-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_extraservices_extraservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='service_description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
