# Generated by Django 4.2.11 on 2024-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_about_image1_about_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y/%m'),
        ),
    ]
