# Generated by Django 4.2.11 on 2024-03-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_about_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='descriptive_info',
            field=models.TextField(blank=True),
        ),
    ]
