# Generated by Django 4.2.11 on 2024-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_about_descriptive_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadResidenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/%y/m')),
            ],
        ),
    ]
