# Generated by Django 4.2.11 on 2024-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_dadresidencedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadresidencedetails',
            name='address',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='dadresidencedetails',
            name='email',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='dadresidencedetails',
            name='phone_number',
            field=models.CharField(blank=True),
        ),
    ]
