# Generated by Django 4.2.11 on 2024-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_dadresidencedetails_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadResidenceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/%y/m')),
                ('email', models.CharField()),
                ('phone_number', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='DadResidenceDetails',
        ),
    ]
