# Generated by Django 4.2.11 on 2024-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_dadresidencedetail_delete_dadresidencedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadresidencedetail',
            name='logo_dark',
            field=models.ImageField(blank=True, upload_to='img/%y/%m'),
        ),
        migrations.AlterField(
            model_name='dadresidencedetail',
            name='logo',
            field=models.ImageField(upload_to='img/%y/%m'),
        ),
    ]
