# Generated by Django 4.2.11 on 2024-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_dadresidencedetail_logo_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y/%m')),
                ('image_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
