# Generated by Django 4.2.11 on 2024-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_galleryimages_delete_roomimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImages',
            new_name='GalleryImage',
        ),
    ]
